apiVersion: v1
kind: Service # Kubernetes resource kind we are creating
metadata:
  name: demo-service
  labels:
    service-label-key: demo-service-label
spec:
  type: NodePort
  ports:
  - name: service-port-name
    protocol: TCP
    port: 8000 # The port that the service is running on in the cluster
    targetPort: 8000 # The port exposed by the service
    nodePort: 31000
  selector:
    app: demo
